site_name: Remove Development on MPCDF cluster
site_description: Sweet sweet remote development on the MPCDF cluster with productivity tools like Jupyter, VSCode, and more.

theme:
  name: readthedocs
  highlightjs: true

repo_url: https://github.com/sabia-group/How-Tos_RemoteDevMPCDF

nav:
  - Home: index.md
  - Configs: configs.md
  - Remote Dev: remote_dev.md
  - Best Practices: best_practices.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets

extra_javascript:
  - javascripts/mathjax.js  # mathjax support
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
